[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/vimproc.vim'

[[plugins]]
repo='Shougo/neomru.vim'

[[plugins]]
repo='Shougo/Unite.vim'
hook_add='''
    nnoremap <silent> sr :<C-u>Unite register<CR>
    nnoremap <silent> sb :<C-u>Unite buffer<CR>
    nnoremap <silent> sf :<C-u>Unite buffer file_mru<CR>
    let g:unite_source_file_mru_limit = 500
'''

[[plugins]]
repo='Shougo/neoyank.vim'
hook_add='''
    nnoremap <silent> sy :<C-u>Unite history/yank<CR>
'''

[[plugins]]
repo='kana/vim-submode'
hook_add="""
    call submode#enter_with('winsize','n','','s>','<C-w>>')
    call submode#enter_with('winsize','n','','s<','<C-w><')
    call submode#enter_with('winsize','n','','s+','<C-w>+')
    call submode#enter_with('winsize','n','','s-','<C-w>-')
    call submode#map('winsize','n','','>','<C-w>>')
    call submode#map('winsize','n','','<','<C-w><')
    call submode#map('winsize','n','','+','<C-w>+')
    call submode#map('winsize','n','','-','<C-w>-')
"""

[[plugins]]
repo='flazz/vim-colorschemes'

[[plugins]]
repo='ujihisa/unite-colorscheme'

[[plugins]]
repo='tpope/vim-fugitive'

[[plugins]]
repo='szw/vim-tags'

[[plugins]]
repo='Shougo/vimfiler.vim'
hook_add='''
    nnoremap <silent> <C-e> :VimFilerExplore -toggle -winwidth=30 -find -force-hide<Cr>
    let g:vimfiler_enable_auto_cd = 1
    "キーマップの変更
    autocmd FileType vimfiler nmap <buffer> F <Plug>(vimfiler_toggle_maximize_window)
    "ファイルを指定せず開いた時のみ起動時にvimfilerを起動
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") && !has("gui_running") | VimFiler -force-quit | endif
'''

[[plugins]]
repo='Lokaltog/vim-easymotion'
hook_add='''
map <space>f <Plug>(easymotion-s)
map <space>j <Plug>(easymotion-jumptoanywhere)
'''

[[plugins]]
repo='cohama/lexima.vim'
hook_add="""
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#)', 'input': '<Right>'})
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#"', 'input': '<Right>'})
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#''', 'input': '<Right>'})
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#]', 'input': '<Right>'})
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#}', 'input': '<Right>'})

    call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'tex'})
    call lexima#add_rule({'char': '$', 'at': '\%#\$', 'input': '<Right>', 'filetype': 'tex'})
    call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'tex'})
    call lexima#add_rule({'char': '<TAB>', 'at': '\%#\$',  'input': '<Right>', 'filetype': 'tex'})
"""

[[plugins]]
repo='Shougo/neocomplcache'

[[plugins]]
repo='Shougo/neosnippet'
hook_add='''
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='fuenor/JpFormat.vim'

[[plugins]]
repo='dhruvasagar/vim-table-mode'

[[plugins]]
repo='tpope/vim-surround'
