#!/bin/bash
set -eu


has(){
    type "$1" > /dev/null 2>&1
}

symlink(){
    [ -e "$2" ] || ln -s "$1" "$2"
}

link(){
    dotfiles=$HOME/dotfiles

    has vim && symlink "$dotfiles/.vimrc" "$HOME/.vimrc"
}

pull(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    git pull origin master
}

push(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    msg=`git status -s | sed -e "s/^ //" -e "s/ /_/g"` || :
    git add .
    git commit -m "$msg"
    git push origin master
}

subcommand="$1"
shift

case $subcommand in
    pull)
        pull
        ;;
    push)
        push
        ;;
    sync)
        pull
        push
        ;;

    link)
        link
        ;;
    *)
        echo "dotfiles commands"
        echo "pull"
        echo "push"
        echo "link"
        ;;
esac