#!/bin/bash
set -eu

pull(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    git pull origin master
}

push(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    git commit -m `git status -s`
    git push origin master
}

subcommand="$1"
shift

case $subcommand in
    pull)
        pull
        ;;
    push)
        push
        ;;
    *)
        echo "dotfiles commands"
        echo "pull"
        echo "push"
        ;;
esac