#!/bin/bash
set -eu

link(){
    aa
}

pull(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    git pull origin master
}

push(){
    dotfiles=$HOME/dotfiles
    cd "$dotfiles"
    msg=`git status -s | sed -e "s/^ //" -e "s/ /_/g"` || :
    git add .
    git commit -m "$msg"
    git push origin master
}

subcommand="$1"
shift

case $subcommand in
    pull)
        pull
        ;;
    push)
        push
        ;;
    *)
        echo "dotfiles commands"
        echo "pull"
        echo "push"
        ;;
esac