#!/bin/bash

# run "curl -sL https://dot.ebiyuu.com | sh" to setup dotfiles

set -eu

# input y/N to one-shot install
echo "This script will install chezmoi and apply dotfiles."

read -p "Dou you prefer one-shot install? [y/N] " yn < /dev/tty
case "$yn" in
    [yY]*) sh -c "$(curl -fsLS https://get.chezmoi.io)" -- init --one-shot --apply ebiyuu1121 ;;
    *) sh -c "$(curl -fsLS https://get.chezmoi.io)" -- init --apply ebiyuu1121 ;;
esac

