#!/bin/bash

# run "curl -sL dot.ebiyuu.com | sh" to setup dotfiles

set -eu

setup(){
    dotfiles=$HOME/dotfiles

    has(){
        type "$1" > /dev/null 2>&1
    }

    symlink(){
        [ -e "$2" ] || ln -s "$1" "$2"
    }


    if ! has "git"; then
        echo "git not installed"
        exit 1
    fi


    cd $HOME

    echo "cloning dotfiles... "
    echo
    git clone git@github.com:ebiyuu1121/dotfiles || git clone https://github.com/ebiyuu1121/dotfiles/ || exit 1

    $HOME/dotfiles/bin/dotfiles link
}

setup
