#!/bin/zsh
# https://qiita.com/arks22/items/a792d9d43d913c373520 から

if sound_info=$(osascript -e 'get volume settings') ; then
  if [ "$(echo $sound_info | awk '{print $8}')" = "muted:false" ]; then
    sound_volume=$(expr $(echo $sound_info | awk '{print $2}' | sed "s/[^0-9]//g") / 6 )
    sound_r="Vol:"$sound_volume"/16"
  else
    sound_r="Mute"
  fi
fi

battery=$(pmset -g ps | awk 'match($0,/[0-9]{1,3}%/){print substr($0, RSTART, RLENGTH - 1)}')'%'
echo $sound_r $battery
