#!/bin/zsh
# https://qiita.com/arks22/items/a792d9d43d913c373520 から

if sound_info=$(osascript -e 'get volume settings') ; then
  if [ "$(echo $sound_info | awk '{print $8}')" = "muted:false" ]; then
    sound_volume=$(expr $(echo $sound_info | awk '{print $2}' | sed "s/[^0-9]//g") / 6 )
    sound_r="Vol:"$sound_volume"/16"
  else
    sound_r="Mute"
  fi
fi

if battery_value=$(pmset -g ps | awk '{ if ( NR==2 ) print $3}' | sed -e "s/;//g") ;then
    if [ ! "$(pmset -g ps | awk '{ if ( NR==2 ) print $4}' | sed -e "s/;//g")" = "discharging" ]; then
        battery_charging="+"
    fi
fi
echo $sound_r $battery_value$battery_charging
