[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_map = ['<C-b>', '<C-p>', 'B']
on_event = ['FocusLost', 'CursorHold']
hook_source = '''
    call ddu#custom#patch_global({
        \   'ui': 'filer',
        \   'sources': [{'name': 'file', 'params': {}}],
        \   'sourceOptions': {
        \     '_': {
        \       'matchers': ['matcher_substring'],
        \     },
        \     'file': {
        \       'columns': ['filename'],
        \     },
        \   },
        \   'kindOptions': {
        \     'file': {
        \       'defaultAction': 'open',
        \     },
        \   },
        \ })

    noremap <silent> <C-b> :call ddu#start()<CR>
    noremap <silent> <C-p> :call ddu#start({'ui': 'ff', 'sources': [{'name': 'file_rec', 'params': {}}]})<CR>
    noremap <silent> B :call ddu#start({'ui': 'ff', 'sources': [{'name': 'buffer', 'params': {}}]})<CR>

    autocmd FileType ddu-ff call s:ddu_my_settings()
    function! s:ddu_my_settings() abort
      nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
      nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
      nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
      nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
    endfunction

    autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
    function! s:ddu_filter_my_settings() abort
      inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
      nnoremap <buffer><silent> <CR> <Cmd>close<CR>
      nnoremap <buffer><silent> q <Cmd>close<CR>
    endfunction

    autocmd FileType ddu-filer call s:ddu_filer_my_settings()
    function! s:ddu_filer_my_settings() abort
      nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#filer#do_action('itemAction')<CR>
      nnoremap <buffer><silent> R <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'rename'})<CR>
      nnoremap <buffer><silent> C <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newFile'})<CR>
      nnoremap <buffer><silent> N <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newDirectory'})<CR>
      nnoremap <buffer><silent> D <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'delete'})<CR>

      nnoremap <buffer><silent> yy <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'copy'})<CR>
      nnoremap <buffer><silent> Y <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'copy'})<CR>
      nnoremap <buffer><silent> M <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'move'})<CR>
      nnoremap <buffer><silent> P <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'paste'})<CR>
      nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
      nnoremap <buffer> o <Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>
      nnoremap <buffer> l <Cmd>call ddu#ui#filer#do_action('expandItem')<CR>
      nnoremap <buffer> h <Cmd>call ddu#ui#filer#do_action('collapseItem')<CR>
      nnoremap <buffer><silent> q <Cmd>call ddu#ui#filer#do_action('quit')<CR>
    endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'
