[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo='flazz/vim-colorschemes'

[[plugins]]
repo='Lokaltog/vim-easymotion'
hook_add='''
map <space>f <Plug>(easymotion-s)
map <space>j <Plug>(easymotion-jumptoanywhere)
'''
