[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lua_hook_post_source = '''
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {
      'lua',
      'ruby',
      'toml',
      'c_sharp',
      'vue',
    },
  },
  --ensure_installed = 'maintained',
}
'''

