[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'nnoremap <leader>r :<c-u>QuickRun<CR>'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    highlight SignColumn ctermbg=black
    highlight GitGutterAdd ctermfg=blue
    highlight GitGutterChange ctermfg=green
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=magenta
    highlight GitGutterAddLine ctermbg=64 "green
    highlight GitGutterChangeLine ctermbg=24 "blue
    highlight GitGutterDeleteLine ctermbg=1 "red
    highlight GitGutterChangeDeleteLine ctermbg=55 "purple
'''

[[plugins]]
repo = 'vim-scripts/grep.vim'
hook_add = '''
    let Grep_Skip_Dirs = '.svn .git node_modules SourcePackages'
    let Grep_Default_Options = '-I'   "ignore binary files
    let Grep_Skip_Files = '*.bak *~' 
    autocmd QuickFixCmdPost *grep* cwindow
'''

[[plugins]]
repo = 'overcache/NeoSolarized'
hook_add = 'colorscheme NeoSolarized'

[[plugins]]
repo = 'thinca/vim-prettyprint'

# This is commented out because it conflicts with du
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends= 'context_filetype.vim'
hook_add = '''
    let g:precious_enable_switchers = {
    \       "*": {
    \           "setfiletype": 0,
    \       },
    \       "toml": {
    \           "setfiletype": 1,
    \       },
    \}
'''

