[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']


[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = [
    'javascript',
    'typescript',
    'javascriptreact',
    'typescriptreact',
    'css',
    'less',
    'scss',
    'json',
    'graphql',
    'vue',
    'html',
    'markdown',
    'tex',
    'python',
    'go',
]
hook_source = '''
    let g:coc_global_extensions = [
        \ 'coc-tsserver',
        \ 'coc-pyright',
        \ 'coc-eslint',
        \ 'coc-html',
        \ 'coc-emmet',
        \ 'coc-css',
        \ 'coc-yaml',
        \ 'coc-highlight',
        \ 'coc-json',
        \ 'coc-vetur',
        \ 'coc-vimtex',
        \ 'coc-go',
        \ 'coc-clangd',
        \ ]
    nnoremap <silent> <space><space> :call CocAction('doHover')<CR>
    nmap <silent> <C-]> <Plug>(coc-definition)
    nmap <silent> <C-t> <Plug>(coc-references)
    nmap <silent> <space>rn <Plug>(coc-rename)
'''

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = [
    'javascript',
    'typescript',
    'javascriptreact',
    'typescriptreact',
    'css',
    'less',
    'scss',
    'json',
    'graphql',
    'vue',
    'html',
    'markdown',
]
hook_source = '''
    "let g:prettier#autoformat = 1
    let g:prettier#autoformat_require_pragma = 0
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_source = '''
  " Note: for profile
  " let g:denops#server#deno_args = [
  "     \ '-q',
  "     \ '--no-check',
  "     \ '--unstable',
  "     \ '-A',
  "     \ '--inspect',
  "     \ ]
'''

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
depends = 'denops.vim'
on_source = 'denops.vim'

