source $HOME/.vim/vimrc.min

source $HOME/.vim/trita.vim

nnoremap <space>s :<c-u>source $MYVIMRC<CR>

" dein
let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if isdirectory(s:dein_repo_dir)
    execute 'set runtimepath+=' . fnamemodify(s:dein_repo_dir, ':p')

    call dein#begin(s:dein_dir)
noremap ; :
        " load toml
        call dein#load_toml('~/.vim/dein.toml', {'lazy': 0})
        call dein#load_toml('~/.vim/dein_lazy.toml', {'lazy': 1})
        call dein#load_toml('~/.vim/ddu.toml', {'lazy': 1})
        if has('nvim')
            call dein#load_toml('~/.vim/dein_nvim.toml', {'lazy': 0, 'merged': 0})
        endif
    call dein#end()

    call dein#save_state()

    " auto install dein plugin
    if dein#check_install()
        call dein#install()
    endif

    filetype plugin indent on
    syntax enable
endif

set formatoptions-=o
set formatoptions-=r
set formatoptions-=c
autocmd BufNewFile,BufRead * set formatoptions-=c formatoptions-=r formatoptions-=o
autocmd FileType * set formatoptions-=c formatoptions-=r formatoptions-=o

augroup MyGroup
    autocmd!
    autocmd BufRead,BufNewFile *.go setlocal noexpandtab
    autocmd BufRead,BufNewFile *.yaml,*.yml,*.json,*.js,*.ts,*.jsx,*.tsx setlocal tabstop=2 shiftwidth=2 softtabstop=2
    au BufRead,BufNewFile *.njk setfiletype html
augroup END

" white spaces
set listchars=tab:>\ ,trail:_
set list

set mouse=a

"オプションの設定"{{{
set backspace=indent,eol,start

set showcmd "入力中のコマンドを表示
set hidden "buffer切り替え時に保存を促さない
set history=1000 "コマンド履歴
set background=dark
set clipboard=unnamedplus,unnamed
set showmatch "対応するかっこを挿入
set matchtime=1
set scrolloff=8
set autoread
set timeoutlen=500

set modelines=5
set hlsearch
set incsearch
nnoremap <silent> <Esc><Esc> :noh<Return>
set ignorecase " 検索文字列が小文字の場合は大文字小文字を区別なく検索する
set smartcase " 検索文字列に大文字が含まれている場合は区別して検索する
"}}}

nnoremap Y y$
nnoremap x "_x

nnoremap <space>l gt
nnoremap <space>h gT
nnoremap <c-n> gt
nnoremap <c-k> gT
nnoremap <c-c> :tabnew<cr>

nnoremap <space> <nop>

" emacs key binding in insert mode
cnoremap <c-n> <down>
cnoremap <c-p> <up>
inoremap <c-b> <left>
cnoremap <c-b> <left>
inoremap <c-f> <right>
cnoremap <c-f> <right>
inoremap <c-a> <home>
cnoremap <c-a> <home>
inoremap <c-e> <end>
cnoremap <c-e> <end>

" esc key
inoremap <silent> jj <ESC>
inoremap <silent> っj <ESC>

if has('nvim')
    set inccommand=split
    set cmdheight=0
endif

syntax on

" .vimlocalの読み込み
if filereadable(expand($HOME.'/local.vimrc'))
    source $HOME/local.vimrc
endif
