# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\

$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\

$direnv\
$env_var\
$sudo\
$cmd_duration\

$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[directory]
truncation_length = 10
truncate_to_repo = false

[localip]
ssh_only = false
disabled = false

